### PR TITLE
feat: adds button on confirm view to go back to Create event page

### PR DESCRIPTION
**Pull request by heron2014**
## PR 1

Related to #234 

Reference:
https://github.com/exponent/ex-navigation#stacknavigation-actions

### CODE REVIEW

**Comment by rickardinho** [comment]
Why do we need another Create button?  Shouldn't we just let them use the one on the bottom right on the tabbar?  The point was more that When I click Create on the tabbar I should always go to a new event being created.

**Comment by heron2014** [comment]
@rickardinho Yes thats right but when the user invites friends and is being redirected to whatsapp we are unable to do any redirection after and the user when comes back from whatsapp is going to see the latest view. So the current solution is to add the button to replace that screen. 

Although I have a thought now. I will check if the screen replacement can be done before redirection to whatapp.

**Comment by rickardinho** [comment]
Yes, thats what I was going to suggest... redirect to Feed, then go to Whatsapp before the user sees the Feed ideally.

**Comment by heron2014** [comment]
@rickardinho After experimenting there are two options:
1. After whatsapp the Confirm view is replaced with the Create screen. So tab navigation is back to normal. User can go wherever he/she wants.

2. After whatsapp user is redirected to Feed but when clicks on Create tab the Confirm view is still there as it was the last time visited. The Confirm view is going to go back to Create once the app is closed and open again. 

I think 1 option is the best solution. Let me know so I will update the PR.

**Comment by rickardinho** [comment]
So can't we do 1 and but redirect to the Feed rather than the Create screen again?
I think option 2 is a non-starter.

**Comment by heron2014** [comment]
@rickardinho that's the problem it seems I can't do two things at the same time. Either I can replace the screen or jumpTo another screen. If I jump to another screen which in this scenario would be Feed I am not able to clear the confirm screen to be create again.

**Comment by rickardinho** [comment]
I'm wondering if this is related to #251 ?  The navigation seems very flaky.  I'm wondering if its the structure of the navigation across the whole tabbar thats causing the issue?

Relating to this issue specifically, could we not say, record a variable before going to whatsapp.  Then on the Create/Feed screens, if there's an OnEnter hook or equivalent, could we not do the clearing based on the value of this variable?  For example, if X = 1, Confirm is replaced with Create, if X=2 Confirm is replaced with Create, then onEnter Create screen it checks and if X=2 it redirects to Feed immediately?

**Comment by heron2014** [comment]
@rickardinho feel free to open and issue with the label of ```enhancement``` to it and we can move the discussion there.

**Pull request merged**
